name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

  lint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: LadingPage-Portfolio-X
      - name: Run eslint
        run: npm run lint
        working-directory: LadingPage-Portfolio-X

  secrets:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install TruffleHog
        run: |
          curl -LJO https://github.com/trufflesecurity/trufflehog/releases/latest/download/trufflehog-linux-amd64
          chmod +x trufflehog-linux-amd64
      - name: Run TruffleHog
        run: ./trufflehog-linux-amd64 filesystem --regex --entropy=True --exclude_paths .gitignore .

  build:
    runs-on: ubuntu-latest
    needs: secrets
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
        working-directory: LadingPage-Portfolio-X
      - name: Build project
        run: npm run build
        working-directory: LadingPage-Portfolio-X

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Vercel CLI
        run: npm install -g vercel
      - name: Pull Vercel environment
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel pull --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID }}
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ vars.VERCEL_ORG_ID }}